### ISSUE TITLE
Problem adding the icon

### ISSUE THREAD

**Issue by nikoo-eshratabadi** [dcasia/icon-action-toolbar#12]
Laravel Version: 10.10
Nova Version: 4.25.1
PHP Version: 8.1.23

i'm having trouble adding icon to my actions with this error. " Method 'icon' not found in Actions\CustomImpersonation "
Although i have required this package, i can't add an icon

    public function actions(NovaRequest $request)
    {
        return [
            CustomImpersonation::make()->showInline()->icon('')
        ];
    }

**Comment by milewski** [comment]
See here: https://github.com/dcasia/icon-action-toolbar/blob/2929c90d153553c0bc1d6072d8bdca4399848f23/src/IconActionToolbarServiceProvider.php#L16C9-L16C15

This package creates a macro on the Action class. If your `CustomImpersonation` class doesn't extend the default Nova Action class, you can work around this by defining the same macro for it.

**Comment by nikoo-eshratabadi** [comment]
i actually do extend the default nova action class . It looks something like this.
`
use Lednerb\ActionButtonSelector\ShowAsButton;

use Laravel\Nova\Actions\Action;
class CustomImpersonation extends Action
{
    use InteractsWithQueue, Queueable, showAsButton;
    public function handle(ActionFields $fields, Collection $models)
    {
        return true;
    }
}
`

**Comment by nikoo-eshratabadi** [comment]
update : i'm using https://packagist.org/packages/lednerb/nova-action-button-selectors
in my action. maybe this is preventing the icon from appearing but when i delete the 'showAsButton' trait from my action, the icon still doesn't work. and it's only visible in the drop down menu ... like this 

![588DAC55-A00F-46A4-B6AF-63C524FB747F_1_201_a](https://github.com/dcasia/icon-action-toolbar/assets/170652568/26c99d7d-194b-4643-bd7e-6bb9de51ebac)



```use Laravel\Nova\Actions\Action;
use Lednerb\ActionButtonSelector\ShowAsButton;

class CustomImpersonation extends Action
{
    use InteractsWithQueue, Queueable, showAsButt
}



and i register it like this


```    public function actions(NovaRequest $request)
    {
        return [
            CustomImpersonation::make()->showInline()->icon('finger-print')
        ];
    }
