### ISSUE TITLE
Wrong link to replicate method

### ISSUE THREAD

**Issue by webard** [dcasia/icon-action-toolbar#13]
Hello,

when resource is allowed to replicate, there is Replicate icon,
<img width="269" alt="image" src="https://github.com/user-attachments/assets/19a283c6-bebd-4d52-a40e-d607fa12f78b">

but clicking it causing 404 due to wrong uRL:
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/b92f39a7-0ffd-4a0e-9377-6617c15f3ec1">

**Comment by sysyl** [comment]
Hello, same problem here!
