### ISSUE TITLE
Infinity loading

### ISSUE THREAD

**Issue by MrFallen** [dcasia/icon-action-toolbar#2]
![image](https://github.com/dcasia/icon-action-toolbar/assets/5339386/6d475fa0-7b11-4aeb-966a-78bea400dd09)

**Comment by milewski** [comment]
Can you see the logs / network tab / console to gather more details of the issue?

**Comment by MrFallen** [comment]
@milewski 
![image](https://github.com/dcasia/icon-action-toolbar/assets/5339386/6bc5c74d-990f-41ff-b426-c89170a31eb8)

**Comment by milewski** [comment]
Hi, I can't reproduce it, can you show me some code, how you are using it, what your action is doing, what is the network response once you click submit, etc...

**Comment by MrFallen** [comment]
I can record video, but later. Cause I am busy right now.

**Comment by MrFallen** [comment]
> Hi, I can't reproduce it, can you show me some code, how you are using it, what your action is doing, what is the network response once you click submit, etc...

https://clipchamp.com/watch/b1KFCgQSusU :)

**Comment by milewski** [comment]
Okay, the issue is your laravel nova version `4.27.12` if you upgrade to `4.27.13` or above it works
