### ISSUE TITLE
Missing basic actions Show on preview and Replicated

### ISSUE THREAD

**Issue by wamesro** [dcasia/icon-action-toolbar#3]
After installing this package, basic actions hidden behind 3 dots will disappear
- Show on preview
- Replicated
- and Delete button in Detail

![Snímka obrazovky 2023-10-20 o 16 21 12](https://github.com/dcasia/icon-action-toolbar/assets/5340873/14d09810-a104-445d-9d74-c13347a1d4fd)

Is there a solution to display them or an example of how to add them manually?

**Comment by milewski** [comment]
Fixed here [v0.0.4](https://github.com/dcasia/icon-action-toolbar/releases/tag/v0.0.4)

**Comment by wamesro** [comment]
Good, the buttons are there
but why is there 2x delete button
and only the right one works

![Snímka obrazovky 2023-10-23 o 9 00 27](https://github.com/dcasia/icon-action-toolbar/assets/5340873/a6fc53b0-8571-4f88-9e4b-98dfbb36ea7e)

Was it not possible to keep the dropdown with 3 dots?
And setting what we want to show inline or in dropdown?

**Comment by milewski** [comment]
Double delete button fixed here: [v0.1.0](https://github.com/dcasia/icon-action-toolbar/releases/tag/v0.1.0)

The option to add `...` is feasible. It's actually not hard to do; it's mostly a copy/paste from the original Nova source code. I'm just a bit short on time now. If you can add it, I'd be happy to merge the pull request.
