### ISSUE TITLE
Problem with icons and labels

### ISSUE THREAD

**Issue by sekru1** [dcasia/icon-action-toolbar#6]
I have two problems with icons and labels:

1.) In the index view, the label in the filter row is not displayed correctly. The button is not wide enough and the icon disappears.
![grafik](https://github.com/dcasia/icon-action-toolbar/assets/25537450/316c82ce-67ea-4ea5-9f3e-e14e20ecee49)

2.) Some icons are not displayed (e.g. "table"), although they are available as heroicons.
![grafik](https://github.com/dcasia/icon-action-toolbar/assets/25537450/dd17c796-b9bb-47bd-add0-5867c7124315)

Nevertheless: fanstatic Nova package!

**Comment by milewski** [comment]
Fixed here: [v0.1.1](https://github.com/dcasia/icon-action-toolbar/releases/tag/v0.1.1), for the icons Nova has upgraded all its icon to hero icons v3, there is no more `table` icon the equivalent now is `table-cells`
